### ISSUE TITLE
Command-Cooldown and Cooldown-Management 

### ISSUE THREAD

**Issue by ibirothe** [selop/tales-of-a#17]
To avoid spamming and enable further gameplay mechanics all commands need a set cooldown.

**Comment by GeorgesAlkhouri** [comment]
Pycord has a more flexible decorator to add cooldowns to commands:

- https://github.com/Pycord-Development/pycord/blob/master/discord/ext/commands/core.py#L2314
- https://github.com/Pycord-Development/pycord/blob/master/examples/cooldown.py

**Comment by ibirothe** [comment]
> Pycord has a more flexible decorator to add cooldowns to commands:
> 
> * https://github.com/Pycord-Development/pycord/blob/master/discord/ext/commands/core.py#L2314
> * https://github.com/Pycord-Development/pycord/blob/master/examples/cooldown.py

We need the Cooldown to be working for Button-Click, rather than per command.

**Comment by selop** [comment]
I guess you should split this issue. We want to distinct features:

- Global cooldown to let users only interact with the game in 1+ second intervals
- A move cooldown only relevant to the button interactions. We either need the same logic for move command + move button or we drop the move command altogether.
